name: donfra-api
services:
  api:
    build:
      context: .
    image: donfra-api:dev
    container_name: donfra-api
    environment:
      - ADDR=:8080
      - PASSCODE=0709
      # - CORS_ORIGIN=http://localhost:3000
      # Optional: base URL used when composing invite links
      # - BASE_URL=http://localhost:3000
    ports:
      - "8080:8080"
    networks:
      - donfra

networks:
  donfra:
    name: donfra
    external: true
